// Import necessary modules and components
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Common/Header/Header";
// Import the type for Metadata if needed
// import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

// Metadata for the document
export const metadata = {
  title: "Watford LLC - Crypto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add any other meta tags or link tags here */}
      </head>
      <body>
        <Header />
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
